[package]
name = "common"
version = "1.0.0"
edition = "2021"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
publish = false

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
