name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build workshop
        shell: bash
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          for i in {1..13}; do
            git merge "origin/chapter-$i"
            if [ "$i" -ne 1 ]; then
              git merge "origin/chapter-$i-solution"
            fi
          done

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Clippy
        run: cargo clippy -- -D warnings
