name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build workshop
        shell: bash
        run: |
          for i in {1..12}; do
            git merge "chapter-$i"
            if [ "$i" -ne 1 ]; then
              git merge "chapter-$i-solution"
            fi
          done

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Clippy
        run: cargo clippy -- -D warnings
